version: "3.8"

services:
  app:
    build:
      context: ./apps/laravel
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./apps/laravel:/var/www
    environment:
      - APP_ENV=local
    depends_on:
      - mysql
      - redis
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost | grep -qE '200|401'",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
      - "443:443"
    volumes:
      - ./apps/laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/certs:/etc/nginx/certs
      - ./docker/nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - app
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -s -o /dev/null -w '%{http_code}' http://localhost | grep -qE '200|401'",
        ]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel_devops_lab_dev
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      laravel:
        aliases:
          - redis

  queue:
    build:
      context: ./apps/laravel
      dockerfile: Dockerfile
    container_name: laravel_queue
    volumes:
      - ./apps/laravel:/var/www
      - ./docker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    command: >
      sh -c "apt-get update &&
             apt-get install -y supervisor &&
             supervisord -c /etc/supervisor/conf.d/laravel-worker.conf"
    depends_on:
      - redis
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - laravel

  horizon:
    build:
      context: ./apps/laravel
      dockerfile: Dockerfile
    container_name: laravel_horizon
    volumes:
      - ./apps/laravel:/var/www
    command: php artisan horizon
    depends_on:
      - redis
    networks:
      - laravel

volumes:
  mysql_data:

networks:
  laravel:
