version: "3.8"

services:
  app:
    build:
      context: ./apps/laravel
      dockerfile: Dockerfile
    container_name: laravel_app_staging
    working_dir: /var/www
    volumes:
      - ./apps/laravel:/var/www
    depends_on:
      - mysql
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx_staging
    ports:
      - "8100:80"
    volumes:
      - ./apps/laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3
    networks:
      - laravel

  mysql:
    image: mysql:8
    container_name: laravel_mysql_staging
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3310:3306"
    volumes:
      - mysql_data_staging:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - laravel

  redis:
    image: redis:alpine
    container_name: laravel_redis_staging
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 5s
      retries: 5
    networks:
      - laravel

  queue:
    build:
      context: ./apps/laravel
      dockerfile: Dockerfile
    container_name: laravel_queue_staging
    volumes:
      - ./apps/laravel:/var/www
      - ./docker/supervisor/laravel-worker.conf:/etc/supervisor/conf.d/laravel-worker.conf
    command: >
      sh -c "apt-get update &&
             apt-get install -y supervisor &&
             supervisord -c /etc/supervisor/conf.d/laravel-worker.conf"
    depends_on:
      - redis
    networks:
      - laravel

  mailhog:
    image: mailhog/mailhog
    container_name: laravel_mailhog_staging
    ports:
      - "8125:8025"
    networks:
      - laravel

volumes:
  mysql_data_staging:

networks:
  laravel:
