name: Laravel Dev CI

on:
  push:
    branches:
      - dev

jobs:
  build:
    name: Build & Test Laravel App
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Clone the code
        uses: actions/checkout@v3

      - name: 🧰 Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql, zip, bcmath
          coverage: none

      - name: 📦 Install dependencies
        run: composer install --prefer-dist --no-progress --no-suggest

      - name: 🧪 Run Laravel tests (if any)
        run: |
          cp .env.example .env
          php artisan key:generate
          php artisan test || echo "No tests found."

      - name: 🚀 Deployment placeholder
        run: echo "✅ Deployment step ready (no server connected)"
